-- database/schema.sql

CREATE DATABASE IF NOT EXISTS imersalab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE imersalab;

CREATE TABLE IF NOT EXISTS USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    nivel_acesso ENUM('admin','editor') NOT NULL DEFAULT 'editor',
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS AMBIENTES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    titulo VARCHAR(200) NOT NULL,
    descricao TEXT NULL,
    imagem_preview VARCHAR(500) NULL,
    imagem_360 VARCHAR(500) NOT NULL,
    categoria_id INT NOT NULL,
    criado_por INT NULL,
    disponivel TINYINT(1) NOT NULL DEFAULT 1,
    data_adicao DATE NOT NULL,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ambientes_categoria FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ambientes_usuario FOREIGN KEY (criado_por) REFERENCES USUARIOS(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PONTOS_NAVEGACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ambiente_id INT NOT NULL,
    destino_id INT NOT NULL,
    label VARCHAR(100) NOT NULL,
    posicao_x FLOAT NOT NULL,
    posicao_y FLOAT NOT NULL,
    posicao_z FLOAT NOT NULL,
    CONSTRAINT fk_pontos_ambiente FOREIGN KEY (ambiente_id) REFERENCES AMBIENTES(id) ON DELETE CASCADE,
    CONSTRAINT fk_pontos_destino FOREIGN KEY (destino_id) REFERENCES AMBIENTES(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
